### ISSUE TITLE
Duplicated specialized pom files

### ISSUE THREAD

**Issue by cesarsotovalero** [castor-software/deptrim#13]
Deptrim is generating multiple specialized poms with the same content. 

The [example project](https://github.com/castor-software/deptrim/tree/main/src/test/resources-its/se/kth/deptrim/DepTrimMojoIT/trimmed_pom_should_be_correct) produces 32 pom files instead of 4. 

It seems to be some bug in the XML dependency manipulation in the pom files so the combinatorial pom generation is not working properly.

**Comment by Deee92** [comment]
@cesarsotovalero, this project has a total of 5 dependencies (including transitive ones), hence the 32 generated pom files.

**Comment by cesarsotovalero** [comment]
@Deee92 but 2/5 dependencies are actually used. Thus only 2 dependencies appear in the 32  specialized poms, which leads to duplications.

**Comment by Deee92** [comment]
I see. 3 of the 5 specialized jars do not have .class files, probably because all of them are unused. But why does depclean report the corresponding dependencies as non-bloated?

**Comment by cesarsotovalero** [comment]
I ran DepClean from the CLI. The DepClean report is correct for this project. I think should be some issue with the pom analysis/manipulation in DepTrim. 

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/13948717/199236307-a5dce1b2-aa7e-41d5-832d-85da98996e8a.png">

**Comment by Deee92** [comment]
Okay, you're right! I'll look at this.
